version: "3.8"

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgis-spatial-analysis-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: spatial_analysis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      # Mount initialization scripts
      - ./data:/docker-entrypoint-initdb.d
      # Persist database data
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d spatial_analysis"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: postgis-spatial-analysis-network
